### ISSUE TITLE
"Select a category" drop-down is missing the categories

### ISSUE THREAD

**Issue by anholt** [GloriaAnholt/ClassAssignments#21]

**Comment by GloriaAnholt** [comment]
This was an experimental solution -- I emptied the constructor function and instead just put regular objects in the filter array and passed them to the createhtml function as arguments, instead of calling it as a method on the object. Fix ended up working, but there's some weird looking code due to the empty constructor.

I'd like more information about how prototypes work and why it was done the other way before refactoring it back.
